version: 2.1
orbs:
  architect: giantswarm/architect@4.2.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: push-rook-operator-to-giantswarm-catalog
          context: "architect"
          executor: "app-build-suite"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "rook-operator"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-api-to-control-plane-app-catalog
          context: architect
          executor: "app-build-suite"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "rook-operator"
          requires:
            - push-rook-operator-to-giantswarm-catalog
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-api-to-kvm-app-collection
          context: architect
          app_name: "rook-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-rook-operator-to-giantswarm-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
