{{- if .Values.global.rookEnabled }}
{{- if .Values.configOverride }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-config-override
  namespace: {{ .Values.global.cephClusterNamespace }}
data:
  config: |
{{ .Values.configOverride | nindent 4 }}
{{- end }}
{{- end }}
