{{- if .Values.global.rookEnabled }}
{{- if ne .Values.global.cephClusterNamespace .Values.operatorNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace: {{ .Values.global.cephClusterNamespace }}
{{ template "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace: {{ .Values.global.cephClusterNamespace }}
{{ template "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
  namespace: {{ .Values.global.cephClusterNamespace }}
{{ template "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-purge-osd
  namespace: {{ .Values.global.cephClusterNamespace }}
{{ template "imagePullSecrets" . }}
{{- end }}
{{- end }}
