apiVersion: v2
appVersion: 1.7.11
dependencies:
  - name: monitoring
    version: 0.2.0
  - name: rook-ceph-cluster
    version: 0.0.1
description: File, Block, and Object Storage Services for your Cloud-Native Environment
engine: gotpl
home: https://github.com/giantswarm/rook-operator-app
icon: https://s.giantswarm.io/app-icons/2/svg/rook-dark.svg
keywords:
- operator
- rook
- ceph
kubeVersion: ">=1.16.0"
maintainers:
  - name: travisn
  - name: galexrt
  - name: jbw976
name: rook-operator
sources:
  - https://github.com/rook/rook
version: 1.1.0
annotations:
  application.giantswarm.io/team: team-rocket
  config.giantswarm.io/version: 1.x.x
restrictions:
  compatibleProviders: ["kvm"]
